name: Deploy React App (Rolling Update)

on:
  push:
    branches:
      - main  # Triggers on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image (v2)
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:v2 .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:v2 ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:v2
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:latest

      - name: Deploy to Docker Swarm (Rolling Update)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling the latest Docker image..."
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:latest

            echo "Performing a rolling update in Docker Swarm..."
            docker service update \
              --image ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:latest \
              --update-parallelism 1 \
              --update-delay 10s \
              --rollback-on-failure \
              --update-failure-action rollback \
              react-app

            echo "Rolling update completed!"
